Setup newrelic
edukorg/go-shortener pull request #3
Opened 2017-06-19 13:26 UTC by rodolfo3

2017-06-19 13:34 UTC, guilhermearaujo requested changes
Indentation is all wrong. Go has some tools that fix is automagically, depending on what editor you're using.

2017-06-19 13:45 UTC, lucasgomide requested changes
use gofmt

2017-06-19 13:45 UTC, lucasgomide commented on main.go
> +  nrCfg := newrelic.NewConfig(mustGetEnv("NEW_RELIC_APP_NAME"), mustGetEnv("NEW_RELIC_LICENSE_KEY"))
Please use the [gofmt](https://golang.org/cmd/gofmt/) command to format your code.

2017-06-19 13:45 UTC, lucasgomide commented on main.go
> +  nrCfg := newrelic.NewConfig(mustGetEnv("NEW_RELIC_APP_NAME"), mustGetEnv("NEW_RELIC_LICENSE_KEY"))
Why are you forcing a lib open-source to use *New Relic* ?

2017-06-19 13:45 UTC, lucasgomide commented on main.go
> +	app newrelic.Application
This is a `package level vars` only accessible on main package.

There is a good [post](http://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html) about it.

Do you really does it ?

2017-06-19 14:30 UTC, rodolfo3 commented on main.go
> +  nrCfg := newrelic.NewConfig(mustGetEnv("NEW_RELIC_APP_NAME"), mustGetEnv("NEW_RELIC_LICENSE_KEY"))
@lucasgomide do you have any other idea or how can we monitoring it, then?

2017-06-19 16:44 UTC, guilhermearaujo commented on main.go
> +  nrCfg := newrelic.NewConfig(mustGetEnv("NEW_RELIC_APP_NAME"), mustGetEnv("NEW_RELIC_LICENSE_KEY"))
@lucasgomide this is our fork, not the original, open-source repo.

2017-06-19 18:53 UTC, guilhermearaujo commented on Godeps/Godeps.json
> +    }
This is still not indented

2017-06-20 13:47 UTC, lucasgomide commented on main.go
> +	app, err = newrelic.NewApplication(nrCfg)
You can initialize those variables only with `:=`
then remove this
```golang
var err error
var app newrelic.Application
```

2017-06-20 13:47 UTC, lucasgomide commented on main.go
> +func getApp() newrelic.Application {
you can rename this method to `setupNewRelic` to explicit what it does

2017-06-20 13:47 UTC, lucasgomide commented on main.go
> +		http.HandleFunc(newrelic.WrapHandleFunc(app, "/", (&handler.RedirectHandler{Client: cfg.RedisClient, Logger: cfg.Logger}).ServeHTTP))
This is bad. But we can improve after it.

2017-08-25 16:21 UTC, closed without merging